server:
  port: 8010
spring:
  application:
    name: carsystem
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/carsdatabase?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379